version: "3"
services:
    db:
        container_name: mydb
        image: mariadb:10.5.8
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ''
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"
